name: Publish MongoDB.Sync NuGet Package

on:
  workflow_run:
    workflows: ["SonarQube Cloud"]
    types:
      - completed

permissions:
  contents: write  # Allow writing to the repository

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Ensure the entire Git history is fetched

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Get Current Sync Version from File
      id: get-sync-version
      shell: bash
      run: |
        if [ ! -f sync_version.txt ]; then
        echo "1.0.0" > sync_version.txt
        fi
        CURRENT_SYNC_VERSION=$(cat sync_version.txt)
        echo "CURRENT_SYNC_VERSION=$CURRENT_SYNC_VERSION" >> $GITHUB_ENV

    - name: Get Current Web Version from File
      id: get-web-version
      shell: bash
      run: |
        if [ ! -f web_version.txt ]; then
        echo "1.0.0" > web_version.txt
        fi
        CURRENT_WEB_VERSION=$(cat web_version.txt)
        echo "CURRENT_WEB_VERSION=$CURRENT_WEB_VERSION" >> $GITHUB_ENV

    - name: Get Current Models Version from File
      id: get-models-version
      shell: bash
      run: |
        if [ ! -f models_version.txt ]; then
        echo "1.0.0" > models_version.txt
        fi
        CURRENT_MODELS_VERSION=$(cat models_version.txt)
        echo "CURRENT_MODELS_VERSION=$CURRENT_MODELS_VERSION" >> $GITHUB_ENV        

    - name: Increment Sync Version
      id: increment-sync-version
      shell: bash
      run: |
        IFS='.' read -r MAJOR MINOR PATCH <<< "${{ env.CURRENT_SYNC_VERSION }}"
        PATCH=$((PATCH + 1))
        NEW_SYNC_VERSION="$MAJOR.$MINOR.$PATCH"
        echo "$NEW_SYNC_VERSION" > ./sync_version.txt  # Specify the file path explicitly
        echo "NEW_SYNC_VERSION=$NEW_SYNC_VERSION" >> $GITHUB_ENV

    - name: Increment Web Version
      id: increment-web-version
      shell: bash
      run: |
        IFS='.' read -r MAJOR MINOR PATCH <<< "${{ env.CURRENT_WEB_VERSION }}"
        PATCH=$((PATCH + 1))
        NEW_WEB_VERSION="$MAJOR.$MINOR.$PATCH"
        echo "$NEW_WEB_VERSION" > ./web_version.txt  # Specify the file path explicitly
        echo "NEW_WEB_VERSION=$NEW_WEB_VERSION" >> $GITHUB_ENV

    - name: Increment Models Version
      id: increment-models-version
      shell: bash
      run: |
        IFS='.' read -r MAJOR MINOR PATCH <<< "${{ env.CURRENT_MODELS_VERSION }}"
        PATCH=$((PATCH + 1))
        NEW_MODELS_VERSION="$MAJOR.$MINOR.$PATCH"
        echo "$NEW_MODELS_VERSION" > ./models_version.txt  # Specify the file path explicitly
        echo "NEW_MODELS_VERSION=$NEW_MODELS_VERSION" >> $GITHUB_ENV

    - name: Commit Updated Version
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add sync_version.txt
        git add web_version.txt
        git add models_version.txt
        git commit -m "Increment version to ${{ env.NEW_SYNC_VERSION }}"
        git push --force

    - name: Build sync project
      run: dotnet build Common/MongoDB.Sync/MongoDB.Sync.csproj --configuration Release

    - name: Build web project
      run: dotnet build Common/MongoDB.Sync.Web/MongoDB.Sync.Web.csproj --configuration Release

    - name: Build Models project
      run: dotnet build Common/MongoDB.Sync.Models/MongoDB.Sync.Models.csproj --configuration Release

    - name: Pack sync NuGet package
      run: dotnet pack Common/MongoDB.Sync/MongoDB.Sync.csproj --configuration Release --output Common/MongoDB.Sync/bin/Release /p:PackageVersion=${{ env.NEW_SYNC_VERSION }}

    - name: Pack web NuGet package
      run: dotnet pack Common/MongoDB.Sync.Web/MongoDB.Sync.Web.csproj --configuration Release --output Common/MongoDB.Sync.Web/bin/Release /p:PackageVersion=${{ env.NEW_WEB_VERSION }}

    - name: Pack web NuGet package
      run: dotnet pack Common/MongoDB.Sync.Models/MongoDB.Sync.Models.csproj --configuration Release --output Common/MongoDB.Sync.Models/bin/Release /p:PackageVersion=${{ env.NEW_MODELS_VERSION }}

    - name: Publish sync to NuGet
      shell: pwsh
      run: |
        $files = Get-ChildItem -Path "Common/MongoDB.Sync/bin/Release" -Filter *.nupkg -Recurse
        if ($files.Count -eq 0) {
          throw "No .nupkg files found in Common/MongoDB.Sync/bin/Release"
        }
        $packagePath = $files[0].FullName
        dotnet nuget push "$packagePath" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}

    - name: Publish web to NuGet
      shell: pwsh
      run: |
        $files = Get-ChildItem -Path "Common/MongoDB.Sync.Web/bin/Release" -Filter *.nupkg -Recurse
        if ($files.Count -eq 0) {
          throw "No .nupkg files found in Common/MongoDB.Sync.Web/bin/Release"
        }
        $packagePath = $files[0].FullName
        dotnet nuget push "$packagePath" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}

    - name: Publish models to NuGet
      shell: pwsh
      run: |
        $files = Get-ChildItem -Path "Common/MongoDB.Sync.Models/bin/Release" -Filter *.nupkg -Recurse
        if ($files.Count -eq 0) {
          throw "No .nupkg files found in Common/MongoDB.Sync.Models/bin/Release"
        }
        $packagePath = $files[0].FullName
        dotnet nuget push "$packagePath" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
